name: CI Pipeline

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Unit Tests
      run: |
        # Commands to run unit tests
        echo "Running unit tests..."
        # Example: npm install && npm test

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v1.2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectKey: 'GitFlow'
        projectName: 'GitFlow'
