name: CI Pipeline

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Verify Java Version
      run: java -version

    - name: Run Unit Tests
      run: |
        # Commands to run unit tests
        echo "Running unit tests..."
        # Example: npm install && npm test

    - name: Install SonarScanner
      run: |
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
        unzip sonar-scanner.zip -d $HOME
        export PATH=$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH

    - name: Run SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=louiswong18_gitflow \
          -Dsonar.projectName=GitFlow \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN
